
[package]
name = "hambooo"
version = "0.1.0"
authors = ["Michael"]
edition = "2021"
build = "build.rs"

readme = "README.md"
license = "MIT and Apache-2.0"
description = "Hamboo - ⌚Smartwatch based on Esp32-S3 chip"
keywords = ["hamboo", "Slint", "esp32", "esp32-s3", "smartwatch"]
repository = "https://github.com/hambooooo/hamboo-rs"

[dependencies]
esp-backtrace = { version = "0.11.1", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
], optional = true }
esp-hal = { version = "0.17.0", features = ["esp32s3", "embedded-hal"], optional = true }
esp-alloc = { version = "0.3.0", optional = true }
esp-println = { version = "0.9.1", features = ["esp32s3", "log"], optional = true }
log = { version = "0.4.21" }

display-interface = { version = "0.5.0", optional = true }
display-interface-spi = { version = "0.5.0", optional = true }
embedded-graphics = { version = "0.8.1", optional = true }
embedded-hal = { version = "1.0.0", optional = true }
embedded-hal-bus = { version = "0.1.0", optional = true }
mipidsi = { git = "https://github.com/almindor/mipidsi", branch = "master", optional = true }
cst816s = { git = "https://github.com/thecodechemist99/cst816s.git", branch = "master", optional = true }
slint = { version = "1.5.1", default-features = false, features = ["compat-1-0"] }

[build-dependencies]
slint-build = { version = "1.5.1" }

[features]
simulator = ["slint/renderer-winit-software", "slint/backend-winit"]
esp32s3 = [
    "slint/unsafe-single-threaded",
    "slint/libm",
    "esp-backtrace",
    "esp-hal",
    "esp-alloc",
    "esp-println",
    "display-interface",
    "display-interface-spi",
    "embedded-graphics",
    "embedded-hal",
    "embedded-hal-bus",
    "mipidsi",
    "cst816s",
]

[profile.dev]
# Rust debug is too slow. 
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
