import { Button, GridBox, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";
import { StatusBar } from "./status-bar.slint";


export component App {
    width: 240px;
    height: 280px;
    in property <string> date_text <=> date.text;
    in property <string> hours_text <=> hours.text;
    in property <string> minutes_text <=> minutes.text;
    in property <bool> datetime_show : true;
    status_bar := StatusBar {
        property <duration> animate_time : 0;
        visible: false;
        y: -280px;
        z: 1;
//        TouchArea {
//            moved => {
//                if (self.pressed_y < 50px) {
//                    status-bar.visible = true;
//                    status-bar.y = -280px + self.mouse_y;
//                }
//            }
//        }
        animate y {
             duration: status-bar.animate_time;
        }
    }
    home := Rectangle {
        opacity: 1;
        z: 0;
        Image {
            source: @image-url("./images/Hamboo.jpg");
            date := Text {
                visible: root.datetime_show;
                x: root.width - self.width - 5px;
                y: (root.height - self.height) / 7;
                text: "30th Apr";
                font-size: 20px;
                color: gold;
            }
            Rectangle{
                visible: root.datetime_show;
                x: 120px;
                y: 50px;
                width: 120px;
                height: 60px;
                hours := Text {
                    x: 0px;
                    text: "12";
                    font-size: 45px;
                    font-weight: 700;
                    color: #fff;
                }
                seconds := Text {
                    x: hours.width + 2px;
                    y: (parent.height - self.height) / 2  - 2px;
                    text: ":";
                    font-size: 40px;
                    font-weight: 700;
                    color: #fff;
                    animate opacity {
                        duration: 1s;
                        iteration-count:-1;
                    }
                    init => {
                        self.opacity = 1;
                    }
                }
                minutes := Text {
                    x: seconds.x + seconds.width + 2px;
                    text: "55";
                    font-size: 45px;
                    font-weight: 700;
                    color: #fff;
                }
            }
        }
        TouchArea {
            moved => {
                if (self.pressed_y < 50px) {
                    status-bar.visible = true;
                    status-bar.animate_time = 0;
                    status-bar.y = -280px + self.mouse_y;

                    home.opacity = (root.height - self.mouse_y) / root.height;

                }
            }
            pointer-event(event) => {
                if (event.kind == PointerEventKind.up) {

                    status-bar.animate_time = 100ms;
                    if (self.mouse_y < root.height / 2) {
                        status-bar.y = -280px;
//                        status-bar.visible = false;
                        home.visible = true;
                        home.opacity = 1;
                    } else {
                        status-bar.y = 0px;
                        home.visible = false;
                    }
                }
            }
        }
    }
}