import { Button, GridBox, VerticalBox , AboutSlint } from "std-widgets.slint";



export component App {
    width: 240px;
    height: 280px;
    in property <string> date_text <=> date.text;
    in property <string> time_text <=> time.text;
    Rectangle {
        Image {
            source: @image-url("./images/Hamboo.jpg");
            date := Text {
                x: root.width - self.width - 15px;
                y: (root.height - self.height) / 8;
                text: "30th Apr";
                font-size: 13px;
                color: gold;
            }
            time := Text {
                x: root.width - self.width - 15px;
                y: (root.height - self.height) / 5;
                text: "12:55";
                font-size: 30px;
                font-weight: 700;
                color: #fff;
            }
            Button {
                property <bool> is_clicked : false;
                text: "Click me";
                clicked => {
                    self.text = self.is_clicked ? "Clicked" : "Click me";
                    self.is_clicked = !self.is_clicked;
                }
            }
        }
    }
}