import { Button, GridBox, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";
import { StatusBar } from "./status-bar.slint";
import { Apps } from "./apps.slint";
import "./fonts/simhei.ttf";

//export global Logic  {
//    pure callback on-button-clicked(string) -> bool;
//}

export component App inherits Window {
    default-font-family: "黑体";
    width: 240px;
    height: 280px;
    in property <string> date_text <=> date.text;
    in property <string> hours_text <=> hours.text;
    in property <string> minutes_text <=> minutes.text;
    in property <bool> datetime_show : true;
    status_bar := StatusBar {
        property <bool> moved: false;
        property <duration> animate_time : 0;
        visible: false;
        y: -280px;
        z: 1;
        animate y, opacity {
            duration: self.animate_time;
        }
        TouchArea {
            z: -1;
            moved => {
                if (self.pressed_y - self.mouse_y > (self.pressed_x > self.mouse_x ? self.pressed_x - self.mouse_x : self.mouse_x - self.pressed_x) + 10px) {
                    home.visible = false;
                    status-bar.moved = true;
                    home.opacity = (root.height - self.mouse_y) / root.height;
                }
            }
            pointer-event(event) => {
                if (event.kind == PointerEventKind.up && status-bar.moved) {
                    status-bar.animate_time = 200ms;
                    status-bar.moved = false;
                    status-bar.y = -280px;
                    home.visible = true;
                    status-bar.opacity = 0;
                    home.opacity = 1;
                }
            }
        }
    }
    apps := Apps {
        property <duration> animate_time : 0;
        visible: false;
        y: 280px;
        z: 1;
        animate y, opacity {
            duration: self.animate_time;
        }
    }
    home := Rectangle {
        opacity: 1;
        z: 0;
        Image {
            height: root.height;
            width: root.width;
            source: @image-url("./images/hamboo.jpg");
            date := Text {
                visible: root.datetime_show;
                x: root.width - self.width - 5px;
                y: (root.height - self.height) / 7;
                text: "30th Apr";
                font-size: 20px;
                color: gold;
            }
            Rectangle{
                visible: root.datetime_show;
                x: 100px;
                y: 50px;
                width: 140px;
                height: 60px;
                hours := Text {
                    x: 0px;
                    text: "12";
                    font-size: 45px;
                    font-weight: 800;
                    color: #fff;
                }
                seconds := Text {
                    x: hours.width + 2px;
                    y: (parent.height - self.height) / 2  - 2px;
                    text: ":";
                    font-size: 40px;
                    font-weight: 700;
                    color: #fff;
                    animate opacity {
                        duration: 1s;
                        iteration-count:-1;
                    }
                    init => {
                        self.opacity = 1;
                    }
                }
                minutes := Text {
                    x: seconds.x + seconds.width + 2px;
                    text: "55";
                    font-size: 45px;
                    font-weight: 700;
                    color: #fff;
                }
            }
        }
        TouchArea {
            x: -0px;
            property <bool> is_moved: false;
            property <int> moved_direction: 1;
            moved => {
                if (self.pressed_y < 50px) {
                    status-bar.visible = true;
                    status-bar.opacity = 1;
                    status-bar.animate_time = 0;
                    status-bar.y = -280px + self.mouse_y;
                    self.is_moved = true;
                    self.moved_direction = 1;
                    //home.opacity = (root.height - self.mouse_y) / root.height;
                }
                if (self.pressed_y > root.height - 50px) {
                    apps.visible = true;
                    apps.opacity = 1;
                    apps.animate_time = 0;
                    apps.y = self.mouse_y;
                    self.is_moved = true;
                    self.moved_direction = 2;
                    //home.opacity = (root.height - self.mouse_y) / root.height;
                }
            }
            pointer-event(event) => {
                if (event.kind == PointerEventKind.up && self.is_moved && self.moved_direction == 1) {
                    self.is_moved = false;
                    status-bar.animate_time = 200ms;
                    if (self.mouse_y < root.height / 2) {
                        status-bar.y = -280px;
                        status-bar.opacity = 0;
                        home.visible = true;
                        home.opacity = 1;
                    } else {
                        status-bar.y = 0px;
                        home.visible = false;
                    }
                }
                if (event.kind == PointerEventKind.up && self.is_moved && self.moved_direction == 2) {
                    self.is_moved = false;
                    apps.animate_time = 200ms;
                    if (self.mouse_y > root.height / 2) {
                        apps.y = 280px;
                        apps.opacity = 0;
                        home.visible = true;
                        home.opacity = 1;
                    } else {
                        apps.y = 0px;
                        home.visible = false;
                    }
                }
            }
        }
    }
}