import { GridBox, Slider, HorizontalBox, VerticalBox, ScrollView } from "std-widgets.slint";

component App inherits Rectangle {
    in-out property <string> name;
    in-out property <image> icon;
    background: rgba(34,43,67, 0.9);
    border-radius: self.height / 2 * 0.5;
    border-color: self.background;
    icon := Image {
        x: 50px;
        width: root.height * 0.8;
        height: self.width;
        source: root.icon;
    }
    Text {
        x: (root.width - icon.width - icon.x);
        text: root.name;
        color: white;
    }
}

export component Apps inherits Rectangle {
    width: 240px;
    height: 280px;
    background: black;
    property <physical-length> item-height: 60px;
    property <physical-length> spacing: 10px;
    property <float> item-with-ratio: 0.9;
    in property <[{name: string, icon: image}]> model: [
        {name: "表盘管理", icon: @image-url("images/app-watch.svg") },
        {name: "天气", icon: @image-url("images/app-weater.svg") },
        {name: "闹钟", icon: @image-url("images/app-clock.svg") },
        {name: "秒表", icon: @image-url("images/app-timer.svg") },
        {name: "NFC", icon: @image-url("images/app-nfc.svg") },
        {name: "运动健康", icon: @image-url("images/app-sports.svg") },
        {name: "指南针", icon: @image-url("images/app-compass.svg") },
        {name: "音乐", icon: @image-url("images/app-music.svg") },
        {name: "智能家居", icon: @image-url("images/app-house.svg") },
        {name: "计算器", icon: @image-url("images/app-calculate.svg") },
        {name: "哔哩哔哩", icon: @image-url("images/app-bilibili.svg") },
        {name: "游戏中心", icon: @image-url("images/app-game.svg") },
        {name: "系统设置", icon: @image-url("images/app-settings.svg") },
    ];
    Flickable {
        viewport-height: (root.item-height + root.spacing) * root.model.length + root.spacing;
        box := VerticalBox {
            y: root.spacing;
            padding-top: 0;
            padding-bottom: 0;
            spacing: root.spacing;
            padding-left: (root.width - root.width * item-with-ratio) / 2;
            for data[index] in root.model: repeat-apps := App {
                name: data.name;
                width: root.width * root.item-with-ratio;
                height: root.item-height;
                icon: data.icon;
            }
        }
    }
    @children
}