import { GridBox, Slider, HorizontalBox, VerticalBox, ScrollView } from "std-widgets.slint";
import { Router, System } from "./global.slint";

component App inherits Rectangle {
    in-out property <string> name;
    in-out property <image> icon;
    callback clicked <=> touch.clicked;
    background: touch.pressed ? white : rgba(34,43,67, 0.9);
    border-radius: self.height / 2 * 0.5;
    border-color: self.background;
    icon := Image {
        x: 50px;
        width: root.height * 0.8;
        height: self.width;
        source: root.icon;
    }
    Text {
        x: (root.width - icon.width - icon.x);
        text: root.name;
        font-size: 13px;
        color: touch.pressed ? black : white;
    }
    touch := TouchArea {}
}

export component Apps inherits Rectangle {
    width: 240px;
    height: 280px;
    background: black;
    in-out property <duration> animate_time : 0;
    property <bool> is_moved: false;
    property <physical-length> item-height: 60px;
    property <physical-length> spacing: 10px;
    property <float> item-with-ratio: 0.9;
    out property <length> flick-y <=> flick-area.viewport-y;
    animate y, opacity {
        duration: self.animate_time;
    }
    goback := Rectangle {
        visible: flick-y == 0;
        y: 3px;
        height: 5px;
        width: root.width * 0.3;
        background: #444;
        border-radius: 2px;
    }
    in property <[{name: string, app: Router, icon: image}]> model: [
        { name: "表盘管理", app: Router.FaceManager, icon: @image-url("images/app-watch.svg") },
        { name: "天气", app: Router.Todo, icon: @image-url("images/app-weater.svg") },
        { name: "闹钟", app: Router.Todo, icon: @image-url("images/app-clock.svg") },
        { name: "秒表", app: Router.StopWatch, icon: @image-url("images/app-timer.svg") },
        { name: "NFC", app: Router.Todo, icon: @image-url("images/app-nfc.svg") },
        { name: "运动健康", app: Router.Todo, icon: @image-url("images/app-sports.svg") },
        { name: "指南针", app: Router.Todo, icon: @image-url("images/app-compass.svg") },
        { name: "音乐", app: Router.Todo, icon: @image-url("images/app-music.svg") },
        { name: "智能家居", app: Router.Todo, icon: @image-url("images/app-house.svg") },
        { name: "计算器", app: Router.Calculator, icon: @image-url("images/app-calculate.svg") },
        { name: "哔哩哔哩", app: Router.Todo, icon: @image-url("images/app-bilibili.svg") },
        { name: "游戏中心", app: Router.Todo, icon: @image-url("images/app-game.svg") },
        { name: "系统设置", app: Router.Settings, icon: @image-url("images/app-settings.svg") },
    ];
    flick-area := Flickable {
        viewport-height: (root.item-height + root.spacing) * root.model.length + root.spacing + goback.height;
        box := VerticalBox {
            y: root.spacing + goback.height;
            padding-top: 0;
            padding-bottom: 0;
            spacing: root.spacing;
            padding-left: (root.width - root.width * item-with-ratio) / 2;
            for data[index] in root.model: repeat-apps := App {
                name: data.name;
                width: root.width * root.item-with-ratio;
                height: root.item-height;
                icon: data.icon;
                clicked => {
                    System.current-page = data.app;
                }
            }
        }
    }
    TouchArea {
        x: 0;
        y: 0;
        width: 100%;
        height: 5%;
        z: 1;
        moved => {
            if (root.flick-y == 0 && self.mouse_y - self.pressed_y > 2px) {
                root.is_moved = true;
                root.visible = false;
                System.current-page = Router.Home;
            }
        }
    }
    @children
}