import { DateTime } from "./global.slint";


// Missing implementation for rotating Image using software renderer
// https://github.com/slint-ui/slint/issues/3068
export component FacePointer inherits Rectangle {
    width: 240px;
    height: 280px;
    Image {
        z: 0;
        source: @image-url("images/face-pointer-bg.svg");
    }
    Image {
        z: 2;
        source: @image-url("images/face-pointer-hour.svg");
        rotation-angle: -60deg;
    }
    Image {
        z: 3;
        source: @image-url("images/face-pointer-minute.svg");
        rotation-angle: 40deg;
    }
    Image {
        z: 4;
        source: @image-url("images/face-pointer-second.svg");
        rotation-angle: 180deg;
        animate rotation-angle {
            duration: 60s;
            iteration-count:-1;
        }
        init => {
            self.rotation-angle = 360deg;
        }
    }
    Text {
        z: 1;
        y: root.height * 0.27;
        text: "HAMBOO";
        font-size: 15px;
        font-weight: 700;
        color: #311;
    }
    Rectangle {
        z: 1;
        y: root.height * 0.6;
        width: 30px;
        height: 20px;
        border-width: 1px;
        border-radius: 5px;
        border-color: #888;
        background: #222;
        Text {
            horizontal-alignment: center;
            vertical-alignment: center;
            text: DateTime.day < 10 ? "0" + DateTime.day : DateTime.day;
            font-size: 14px;
            font-weight: 600;
            color: #bbb;
        }
    }
    Text {
        z: 1;
        y: root.height * 0.15;
        text: "12";
        font-size: 30px;
        color: white;
    }
    Text {
        z: 1;
        y: (root.height - self.height) / 2;
        x: root.width * 0.85 - self.width;
        text: "3";
        font-size: 30px;
        color: white;
    }
    Text {
        z: 1;
        y: root.height * 0.85 - self.height;
        text: "6";
        font-size: 30px;
        color: white;
    }
    Text {
        z: 1;
        y: (root.height - self.height) / 2;
        x: root.width * 0.15;
        text: "9";
        font-size: 30px;
        color: white;
    }
}