import { Button } from "./compontents/button.slint";
import { GoHome } from "./compontents/go-home.slint";
import { Router, System } from "./global.slint";
import { FacePointer } from "./face-pointer.slint";
import { FaceHamboo } from "./face-hamboo.slint";
import { FaceDigital } from "./face-digital.slint";
import { FacePicture } from "./face-picture.slint";

export component FaceManager inherits Rectangle {
    width: 240px;
    height: 280px;
    background: gray;

    property <int> max-index: 3;
    property <int> crt-index: 0;
    property <physical-length> fa-x: -160px;
    property <physical-length> fb-x: 30px;
    property <physical-length> fc-x: 220px;

    GoHome {}
    // index = 0
    if crt-index == max-index || crt-index <= 1 : FaceHamboo {
        x: crt-index == max-index ? fa-x : crt-index == 0 ? fb-x : fc-x;
        y: 30px;
        height: 200px;
        width: 180px;
    }
    // index = 1
    if crt-index >= 0 && crt-index <= 2 : FacePointer {
        x: crt-index == 0 ? fa-x : crt-index == 1 ? fb-x : fc-x;
        y: 30px;
        height: 200px;
        width: 180px;
    }
    // index = 2
    if crt-index >= 1 && crt-index <= 3 : FaceDigital {
        x: crt-index == 1 ? fa-x : crt-index == 2 ? fb-x : fc-x;
        y: 30px;
        height: 200px;
        width: 180px;
        font-size: 90px;
    }
    // index = 3
    if crt-index >= 2 || crt-index == 0 : FacePicture {
        x: crt-index == 2 ? fa-x : crt-index == 3 ? fb-x : fc-x;
        y: 30px;
        height: 200px;
        width: 180px;
    }
    Button {
        y: 240px;
        width: 50px;
        height: 30px;
        background: #aaa;
        text: "禁用";
        font-color: black;
    }
    TouchArea {
        y: 40px;
        width: root.width;
        height: 200px;
        clicked => {
            crt-index += 1;
            crt-index = crt-index > 3 ? 0 : crt-index;
        }
    }
}