import { DateTime } from "./global.slint";

export component FaceHamboo inherits Rectangle {
    width: 240px;
    height: 280px;
    property <float> zoom : self.height / 280px;
    Image {
        height: root.height;
        width: root.width;
        source: @image-url("./images/hamboo.jpg");
        date := Text {
            x: root.width - self.width - 5px;
            y: (root.height - self.height) / 7 * zoom;
            // DateTime.weekday_cn not work ???
            property <[string]> WEEKDAYS_CN: ["一", "二", "三", "四", "五", "六", "日"];
            text: @tr("{}月{}日 星期{}", DateTime.month, DateTime.day, WEEKDAYS_CN[DateTime.weekday]);
            font-size: 12px * zoom;
            color: white;
        }
        Rectangle{
            x: root.width - self.width;
            y: 50px * zoom;
            width: 120px * zoom;
            height: 60px * zoom;
            hours := Text {
                x: 0px;
                text: DateTime.hours< 10 ? "0" + DateTime.hours : DateTime.hours;
                font-size: 45px * zoom;
                font-weight: 700 * zoom;
                color: #fff;
            }
            seconds := Text {
                x: hours.width + 2px;
                y: ((parent.height - self.height) / 2  - 2px) * zoom;
                text: ":";
                font-size: 40px * zoom;
                color: #fff;
            }
            minutes := Text {
                x: seconds.x + seconds.width + 2px;
                text: DateTime.minutes< 10 ? "0" + DateTime.minutes : DateTime.minutes;
                font-size: 45px * zoom;
                font-weight: 700 * zoom;
                color: #fff;
            }
        }
    }
    @children
}