import { DateTime } from "./global.slint";

export component FaceHamboo inherits Rectangle {
    Image {
        height: root.height;
        width: root.width;
        source: @image-url("./images/hamboo.jpg");
        date := Text {
            x: root.width - self.width - 5px;
            y: (root.height - self.height) / 7;
            // DateTime.weekday_cn not work ???
            property <[string]> WEEKDAYS_CN: ["一", "二", "三", "四", "五", "六", "日"];
            text: @tr("{}月{}日 星期{}", DateTime.month, DateTime.day, WEEKDAYS_CN[DateTime.weekday]);
            font-size: 13px;
            color: white;
        }
        Rectangle{
            x: 100px;
            y: 50px;
            width: 140px;
            height: 60px;
            hours := Text {
                x: 0px;
                text: DateTime.hours< 10 ? "0" + DateTime.hours : DateTime.hours;
                font-size: 45px;
                font-weight: 800;
                color: #fff;
            }
            seconds := Text {
                x: hours.width + 2px;
                y: (parent.height - self.height) / 2  - 2px;
                text: ":";
                font-size: 40px;
                font-weight: 700;
                color: #fff;
            }
            minutes := Text {
                x: seconds.x + seconds.width + 2px;
                text: DateTime.minutes< 10 ? "0" + DateTime.minutes : DateTime.minutes;
                font-size: 45px;
                font-weight: 800;
                color: #fff;
            }
        }
    }
    @children
}