export enum Router {
    Home,
    StatusBar,
    Settings,
    Apps
}

export enum Face {
    Hamboo,
    Digital
}

export global System {
    in-out property <Router> current-page : Home;
    in-out property <Face> current-face : Hamboo;
    in-out property <bool> wifi-enable : false;
    in-out property <bool> bluetools-enable : false;
    in-out property <int> brightness : 50;
    in-out property <int> volume : 30;

    pure callback brightness-change(int);
}

export global Battery  {
    in property <bool> charging : false;
    in property <int> percent : 100;
}

export global DateTime  {
    in property <int> year : 24;
    in property <int> month : 6;
    in property <int> weekday : 6;
    in property <int> day : 9;
    in property <int> hours : 12;
    in property <int> minutes  : 0;
    in property <int> seconds : 0;
}