export enum Router {
    Home,
    StatusBar,
    Settings,
    Apps,
    Calculator,
    StopWatch,
    Todo
}

export global System {
    in property <length> screen-width: 240px;
    in property <length> screen-height: 280px;
    in-out property <Router> current-page: Home;
    in-out property <int> current-face-id: 0;
    in-out property <bool> wifi-enable: false;
    in-out property <bool> bluetools-enable: false;
    in-out property <int> brightness: 50;
    in-out property <int> volume: 30;

    pure callback brightness-change(int);
    // year, month, weekday, day, hours, minutes, seconds
    pure callback set-datetime(int, int, int, int, int, int, int);
}

export global Battery {
    in property <bool> charging: false;
    in property <int> percent: 100;
}

export global DateTime {
    in property <int> year: 24;
    in property <int> month: 6;
    in property <int> weekday: 6;
    in property <int> day: 9;
    in property <int> hours: 12;
    in property <int> minutes: 0;
    in property <int> seconds: 0;

    property <[string]> WEEKDAYS_CN: ["一", "二", "三", "四", "五", "六", "日"];
    out property <string> weekday_cn: WEEKDAYS_CN[weekday];
}
