import { Button, GridBox, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";
import { StatusBar } from "./status-bar.slint";
import { Apps } from "./apps.slint";
import { Settings } from "./settings.slint";
import { Router, System } from "./global.slint";
import { FaceHamboo } from "./face-hamboo.slint";
import { FaceDigital } from "./face-digital.slint";
import { FacePointer } from "./face-pointer.slint";
import { Calculator } from "./calculator.slint";
import "./fonts/simhei.ttf";

export component Home inherits Rectangle {
    width: 240px;
    height: 280px;
    status_bar := StatusBar {
        visible: false;
        y: root.height * -1;
        z: 1;
    }
    apps := Apps {
        visible: false;
        y: root.height;
        z: 1;
    }
    home := Rectangle {
        if System.current-face-id == 0: FaceHamboo {}
        if System.current-face-id == 1: FaceDigital {}
        if System.current-face-id == 2: FacePointer {}

        TouchArea {
            x: 0;
            property <bool> is_moved: false;
            property <int> moved_direction: 1;
            moved => {
                if (self.pressed_y < 50px) {
                    status-bar.visible = true;
                    status-bar.opacity = 1;
                    status-bar.animate_time = 0;
                    status-bar.y = self.mouse_y - root.height;
                    self.is_moved = true;
                    self.moved_direction = 1;
                }
                else if (self.pressed_y > root.height - 50px) {
                    apps.visible = true;
                    apps.opacity = 1;
                    apps.animate_time = 0;
                    apps.y = self.mouse_y;
                    self.is_moved = true;
                    self.moved_direction = 2;
                }
                else if (self.pressed_x - self.mouse_x > (self.pressed_y > self.mouse_y ? self.pressed_y - self.mouse_y : self.mouse_y - self.pressed_y) + 50px) {
                    self.is_moved = true;
                    self.moved_direction = 3;
                }
                else if (self.mouse_x - self.pressed_x > (self.pressed_y > self.mouse_y ? self.pressed_y - self.mouse_y : self.mouse_y - self.pressed_y) + 50px) {
                    self.is_moved = true;
                    self.moved_direction = 4;
                }
            }
            pointer-event(event) => {
                if (event.kind == PointerEventKind.up && self.is_moved && self.moved_direction == 1) {
                    self.is_moved = false;
                    status-bar.animate_time = 200ms;
                    if (self.mouse_y < root.height / 2) {
                        status-bar.y = root.height * -1;
                        status-bar.opacity = 0;
                        home.visible = true;
                        home.opacity = 1;
                    } else {
                        status-bar.y = 0px;
                    }
                }
                if (event.kind == PointerEventKind.up && self.is_moved && self.moved_direction == 2) {
                    self.is_moved = false;
                    apps.animate_time = 200ms;
                    if (self.mouse_y > root.height / 2) {
                        apps.y = root.height;
                        apps.opacity = 0;
                        home.visible = true;
                        home.opacity = 1;
                    } else {
                        apps.y = 0px;
                    }
                }
                if (event.kind == PointerEventKind.up && self.is_moved && self.moved_direction == 3) {
                    System.current-face-id += 1;
                    System.current-face-id = System.current-face-id > 2 ? 0 : System.current-face-id;
                }
                if (event.kind == PointerEventKind.up && self.is_moved && self.moved_direction == 4) {
                    System.current-face-id -= 1;
                    System.current-face-id = System.current-face-id < 0 ? 2 : System.current-face-id;
                }
            }
        }
    }
}