import { GridBox, Slider, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Slider } from "./compontents/slider.slint";
import { Button } from "./compontents/button.slint";
import { GoHome } from "./compontents/go-home.slint";
import { System, DateTime } from "./global.slint";

enum SettingsItem {
    None,
    Date,
    Time,
    About
}

component NumButton inherits HorizontalBox {
    in property <string> title;
    in-out property <int> value;
    in property <int> min-value : 0;
    in property <int> max-value : 100;
    Text {
        text: @tr("{} ：", title);
        color: white;
        font-size: 20px;
    }
    btn-sub := Button {
        text: "<";
        clicked => {
            value -= 1;
            value = value < min-value ? max-value : value;
        }
        background: black;
        font-color: white;
    }
    Text {
        text: value;
        color: white;
        font-size: 20px;
    }
    btn-add := Button {
        text: ">";
        clicked => {
            root.value += 1;
            value = value > max-value ? min-value : value;
        }
        background: black;
        font-color: white;
    }
    
}

export component Settings inherits Rectangle {
    width: 240px;
    height: 280px;
    property <SettingsItem> active-table : None;
    background: black;
    GoHome {}
    if root.active-table == SettingsItem.None : VerticalBox {
        padding-top: 40px;
        Button {
            height: 50px;
            text: "设置日期";
            clicked => {
                root.active-table = SettingsItem.Date;
            }
        }
        Button {
            height: 50px;
            text: "设置时间";
            clicked => {
               root.active-table = SettingsItem.Time;
            }
        }
        Button {
            height: 50px;
            text: "关于";
            clicked => {
              root.active-table = SettingsItem.About;
            }
        }
    }
    if root.active-table == SettingsItem.Date : VerticalBox {
        padding-top: 40px;
        year := NumButton {
            title: "年";
            width: 100%;
            value: DateTime.year;
            min-value: 0;
            max-value: 99;
        }
        month := NumButton {
            title: "月";
            width: 100%;
            value: DateTime.month;
            min-value: 1;
            max-value: 12;
        }
        weekday := NumButton {
            title: "周";
            width: 100%;
            value: DateTime.weekday + 1;
            min-value: 1;
            max-value: 7;
        }
        day := NumButton {
            title: "日";
            width: 100%;
            value: DateTime.day;
            min-value: 1;
            max-value: 31;
        }
        Button {
            height: 50px;
            text: "确定";
            clicked => {
                System.set-datetime(year.value, month.value, weekday.value - 1, day.value, DateTime.hours, DateTime.minutes, DateTime.seconds);
                root.active-table = SettingsItem.None;
            }
        }
    }
    if root.active-table == SettingsItem.Time : VerticalBox {
        padding-top: 40px;
        hours := NumButton {
            title: "时";
            width: 100%;
            value: DateTime.hours;
            min-value: 0;
            max-value: 23;
        }
        minutes := NumButton {
            title: "分";
            width: 100%;
            value: DateTime.minutes;
            min-value: 0;
            max-value: 59;
        }
        seconds := NumButton {
            title: "秒";
            width: 100%;
            value: DateTime.seconds;
            min-value: 0;
            max-value: 59;
        }
        Button {
            height: 50px;
            text: "确定";
            clicked => {
                System.set-datetime(DateTime.year, DateTime.month, DateTime.weekday, DateTime.day, hours.value, minutes.value, seconds.value);
                root.active-table = SettingsItem.None;
            }
        }
    }
    if root.active-table == SettingsItem.About : VerticalBox {
        padding-top: 40px;
        Text {
            text: "版本号：0.1.0-20240609001";
            color: white;
        }
        Text {
            text: "仓库地址：https://github.com/hamboooo/hamboo-rs";
            color: white;
        }
        Button {
            height: 50px;
            text: "确定";
            clicked => {
                root.active-table = SettingsItem.None;
            }
        }
    }
    @children

}