import { Button, GridBox, Slider, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Slider } from "./compontents/slider.slint";

export component StatusBar inherits Rectangle {
    width: 240px;
    height: 280px;
    background: @linear-gradient(45deg, #9fafa6 0%, #ebe8e1 50%, #f6afaf 100%);
    GridBox {
        padding-left: 0;
        padding-top: 0;
        property <physical-length> button-size: 45px;
        Row {
            Rectangle {
                background: #eee;
                border-radius: 10px;
                GridBox {
                    Row {
                        Button {
                            height: button-size;
                            width: button-size;
                            icon: @image-url("images/icon-airplane-mode.svg");
                        }
                        Button {
                            height: button-size;
                            width: button-size;
                            icon: @image-url("images/icon-disable-alarm.svg");
                        }
                    }
                    Row{
                        Button {
                             height: button-size;
                             width: button-size;
                             icon: @image-url("images/icon-wifi.svg");
                         }
                         Button {
                             height: button-size;
                             width: button-size;
                             icon: @image-url("images/icon-bluetools.svg");
                         }
                    }
                }
            }
            Rectangle {
                background: #eee;
                border-radius: 10px;
                GridBox {
                    Row {
                        Button {
                            height: button-size;
                            width: button-size;
                            icon: @image-url("images/icon-calculate.svg");
                        }
                        Button {
                            height: button-size;
                            width: button-size;
                            icon: @image-url("images/icon-eye-protection-mode.svg");
                        }
                    }
                    Row {
                        Button {
                            height: button-size;
                            width: button-size;
                            icon: @image-url("images/icon-light.svg");
                        }
                        Button {
                            height: button-size;
                            width: button-size;
                            icon: @image-url("images/icon-settings.svg");
                        }
                    }
                }
            }
        }

        Row {
            Slider {
                colspan: 2;
                width: 240px;
                value: 20;
                Image {
                    x: 10px;
                    width: 15px;
                    source: @image-url("./images/icon-brightness.svg");
                }
            }
        }
        Row {
            Slider {
                colspan: 2;
                width: 240px;
                value: 50;
                Image {
                    x: 10px;
                    width: 15px;
                    source: parent.value > 0 ? @image-url("./images/icon-volume.svg") : @image-url("./images/icon-volume-disable.svg");
                }
            }
        }
        Row {
            Rectangle {
                border-color: gray;
                border-width: 1px;
                colspan: 2;
                VerticalBox {
                    padding:0;
                    spacing: 0;
                    HorizontalBox {
                        padding-top: 10px;
                        padding-bottom: 0;
                        Image {
                            width: 50px;
                            height: 60px;
                            source: @image-url("./images/music.jpg");
                        }
                        GridBox {
                            padding-top: 5px;
                            Row {
                                Text {
                                    colspan: 3;
                                    text: "[Golden Hour]She's got Gliter for skin";
                                    overflow: elide;
                                }
                            }
                            Row {
                                Button {
                                    text: "<";
                                }
                                Button {
                                    property <bool> click: false;
                                    text: "▶";
                                    clicked => {
                                        self.text = self.click ? "▶" : "| |";
                                        self.click = !self.click;
                                    }
                                }
                                Button {
                                    text: ">";
                                }
                            }
                        }
                    }
                    HorizontalBox {
                        padding-top: 0px;
                        padding-bottom: 5px;
                        spacing: 5px;
                        Text {
                            width: 18px;
                            text: "1.30";
                            font-size: 10px;
                        }
                        Rectangle {
                            width: 170px;
                            background: #888;
                            border-radius: 5px;
                            height: 10px;
                        }
                        Text {
                            width: 18px;
                            text: "-0.1";
                            font-size: 10px;
                        }
                    }
                }
            }
        }
    }
    @children

}