import { Button, GridBox, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";
import { GoHome } from "./compontents/go-home.slint";
import { DateTime } from "./global.slint";

export component StopWatch inherits Rectangle {
    width: 240px;
    height: 280px;
    background: black;
    property <bool> running;
    property <int> start-time;
    property <int> minutes : (DateTime.seconds + DateTime.minutes * 60 - start-time) / 60;
    property <int> seconds : DateTime.seconds + DateTime.minutes * 60 - start-time - minutes * 60;
    property <string> display : @tr("{}:{}.00", minutes < 10 ? "0" + minutes : minutes, seconds < 10 ? "0" + seconds : seconds);
    property <string> result : "00:00.00";
    GoHome {}
    VerticalBox {
        padding-top: 40px;
        alignment: center;
        if running : Text {
            horizontal-alignment: center;
            text: display;
            font-size: 50px;
            color: white;
        }
        if !running : Text {
            horizontal-alignment: center;
            text: result;
            font-size: 50px;
            color: white;
        }
        HorizontalBox {
            Button {
                text:  "复位";
                clicked => {
                    result = "00:00.00";
                }
            }

            Button {
                text:  running ? "停止" : "开始";
                clicked => {
                    if (running) {
                        result = display;
                    } else {
                        start-time = DateTime.seconds + DateTime.minutes * 60;
                    }
                    running = !running;
                }
            }
        }

    }

}