import { GoHome } from "./compontents/go-home.slint";
import { Router, System } from "./global.slint";

export component Todo inherits Rectangle {
    width: 240px;
    height: 280px;
    background: black;
    GoHome {}
    Text {
        padding-top: 40px;
        text: "// todo... ;";
        font-size: 30px;
        color: white;
    }
    TouchArea {
        moved => {
            System.current-page = Router.Home;
        }
        clicked => {
            System.current-page = Router.Home;
        }
    }
}