import { Button, GridBox, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";
import { StatusBar } from "./apps/status-bar.slint";
import { AppLauncher } from "./apps/app-launcher.slint";
import { FaceContainer } from "./apps/face-container.slint";
import "./assets/fonts/simhei.ttf";

export global Global  {
//    pure callback on-button-clicked(string) -> bool;
    in-out property <int> active-face : 1;
}

export component UI inherits Window {
    default-font-family: "黑体";
    width: 240px;
    height: 280px;
    status_bar := StatusBar {
        property <bool> moved: false;
        property <duration> animate_time : 0;
        visible: false;
        y: -280px;
        z: 1;
        animate y, opacity {
            duration: self.animate_time;
        }
        TouchArea {
            z: -1;
            moved => {
                if (self.pressed_y - self.mouse_y > (self.pressed_x > self.mouse_x ? self.pressed_x - self.mouse_x : self.mouse_x - self.pressed_x) + 10px) {
                    face.visible = false;
                    status-bar.moved = true;
                    face.opacity = (root.height - self.mouse_y) / root.height;
                }
            }
            pointer-event(event) => {
                if (event.kind == PointerEventKind.up && status-bar.moved) {
                    status-bar.animate_time = 200ms;
                    status-bar.moved = false;
                    status-bar.y = -280px;
                    face.visible = true;
                    status-bar.opacity = 0;
                    face.opacity = 1;
                }
            }
        }
    }
    apps := AppLauncher {
        property <duration> animate_time : 0;
        visible: false;
        y: 280px;
        z: 1;
        animate y, opacity {
            duration: self.animate_time;
        }
    }
    face := FaceContainer {
        z: 0;
        active-face: Global.active-face;
        TouchArea {
            property <bool> is_moved: false;
            property <int> moved_direction: 1;
            moved => {
                if (self.pressed_y < 50px) {
                    status-bar.visible = true;
                    status-bar.opacity = 1;
                    status-bar.animate_time = 0;
                    status-bar.y = -280px + self.mouse_y;
                    self.is_moved = true;
                    self.moved_direction = 1;
                    //parent.opacity = (root.height - self.mouse_y) / root.height;
                }
                if (self.pressed_y > root.height - 50px) {
                    apps.visible = true;
                    apps.opacity = 1;
                    apps.animate_time = 0;
                    apps.y = self.mouse_y;
                    self.is_moved = true;
                    self.moved_direction = 2;
                    //parent.opacity = (root.height - self.mouse_y) / root.height;
                }
            }
            pointer-event(event) => {
                if (event.kind == PointerEventKind.up && self.is_moved && self.moved_direction == 1) {
                    self.is_moved = false;
                    status-bar.animate_time = 200ms;
                    if (self.mouse_y < root.height / 2) {
                        status-bar.y = -280px;
                        status-bar.opacity = 0;
                        parent.visible = true;
                        parent.opacity = 1;
                    } else {
                        status-bar.y = 0px;
                        parent.visible = false;
                    }
                }
                if (event.kind == PointerEventKind.up && self.is_moved && self.moved_direction == 2) {
                    self.is_moved = false;
                    apps.animate_time = 200ms;
                    if (self.mouse_y > root.height / 2) {
                        apps.y = 280px;
                        apps.opacity = 0;
                        parent.visible = true;
                        parent.opacity = 1;
                    } else {
                        apps.y = 0px;
                        parent.visible = false;
                    }
                }
            }
        }
    }
}