import { Button, GridBox, VerticalBox, HorizontalBox, AboutSlint } from "std-widgets.slint";
import { StatusBar } from "./status-bar.slint";
import { Apps } from "./apps.slint";
import { Settings } from "./settings.slint";
import { Router, Battery, DateTime, System } from "./global.slint";
import { FaceHamboo } from "./face-hamboo.slint";
import { Calculator } from "./calculator.slint";
import { Home } from "./home.slint";
import { Todo } from "./todo.slint";
import "./fonts/simhei.ttf";

export { Router, Battery, DateTime, System }

export component UI inherits Window {
    default-font-family: "黑体";
    width: System.screen-width;
    height: System.screen-height;
    if System.current-page == Router.Home : Home { }
    if System.current-page == Router.StatusBar : StatusBar { }
    if System.current-page == Router.Apps : Apps { }
    if System.current-page == Router.Settings : Settings { }
    if System.current-page == Router.Calculator : Calculator { }
    if System.current-page == Router.Todo : Todo { }
}